### ISSUE TITLE
Is this abandonware?

### ISSUE THREAD

**Issue by igor-kobzev** [Cangjians/ibus-cangjie#101]
I see that the latest release was in 2015.
On the other hand, there is ibus-table repo in github that also includes cangjie method.
So is this project abandoned in favor of ibus-table?

**Comment by bochecha** [comment]
Not at all.

In fact I created ibus-cangjie because ibus-table was pretty bad.

So it's always been an explicit goal to replace ibus-table by ibus-cangjie.

However due to unforeseen personal reasons I haven't been able to work on the Cabgjie stack for a while, which is why the absence of recent activity. :(


-- 
Mathieu 

Le 22 décembre 2021 08:30:29 GMT+01:00, "Igor 祐龢 Kobzev" ***@***.***> a écrit :
>I see that the latest release was in 2015.
>On the other hand, there is ibus-table repo in github that also includes cangjie method.
>So is this project abandoned in favor of ibus-table?
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/Cangjians/ibus-cangjie/issues/101
>You are receiving this because you are subscribed to this thread.
>
>Message ID: ***@***.***>
-- 
Envoyé de mon appareil Android avec Courriel K-9 Mail. Veuillez excuser ma brièveté.

**Comment by WhiteCzar** [comment]
I see! I'm sorry for the misunderstanding.
Hope you can find some time to get back to this project (or maybe someone decided to work on it instead). Diversity is always good in software!

**Comment by mbridon** [comment]
I'm trying to get back to this project, so I'm cloding this issue. :wink:
