### ISSUE TITLE
GLib-GIO-ERROR

### ISSUE THREAD

**Issue by teamblubee** [Cangjians/ibus-cangjie#88]
I created a port, built and installed
libcangjie
pycangjie
ibus-cangjie

Even after the installation I get this error:
```shell
(process:6236): GLib-GIO-ERROR **: Settings schema 'org.cangjians.ibus.cangjie' is not installed
```

This is the full verbose output
```shell
sys:1: PyGIWarning: IBus was imported without specifying a version first. Use gi.require_version('IBus', '1.0') before import to ensure that the right version gets loaded.

(process:6236): GLib-GIO-ERROR **: Settings schema 'org.cangjians.ibus.cangjie' is not installed

ibus-chewing-Message: * focus_out(): statusFlags=17
ibus-chewing-Message: * focus_in(): statusFlags=3
ibus-chewing-Message: ***** set_capabilities(29): statusFlags=17
ibus-chewing-Message: * focus_out(): statusFlags=17
ibus-chewing-Message: * focus_in(): statusFlags=3
ibus-chewing-Message: ***** set_capabilities(8): statusFlags=17
ibus-chewing-Message: process_key_event() result=0
ibus-chewing-Message: process_key_event() result=0
```

What exactly is missing?

**Comment by bochecha** [comment]
Hi there,

To debug this I'll need a bit more information. First of all, how did you install ibus-cangjie? Can you paste the **exact** list of commands you ran? (from your shell history)

Also, what do you mean by "I created a port"?

**Comment by teamblubee** [comment]
hi @bochecha 

a port, is taking your software and making it available to the *BSD ecosystem, specifically FreeBSD: https://www.freebsd.org/ports/categories-grouped.html

I actually sorted the issue out, I needed to run 
```shell
glib-compile-schemas
```

to get the glib schemas to get installed.

Although, I had to make several modifications to your configure scripts.

Maybe you would be able to upstream some of these changes if they don't conflict with your project on other platforms as well?

autogen.sh patch
```shell
--- autogen.sh.orig	2015-03-29 15:19:21 UTC
+++ autogen.sh
@@ -1,4 +1,4 @@
-#!/bin/bash
+#!/bin/sh
 
 set -e
 set -x
```
patch configure.ac
```
--- configure.ac.orig	2018-01-21 22:00:48.892985000 +0100
+++ configure.ac	2018-01-21 22:00:30.658013000 +0100
@@ -15,8 +15,8 @@
 IT_PROG_INTLTOOL([0.35.0])
 
 # i18n
-AM_GNU_GETTEXT([external])
-AM_GNU_GETTEXT_VERSION(0.17)
+#AM_GNU_GETTEXT([external])
+#AM_GNU_GETTEXT_VERSION(0.17)
 
 # Note: If you change GETTEXT_PACKAGE below, you will also need to change it
 #       in src/config.py, or find a way to de-hardcode it there.
```

**Comment by bochecha** [comment]
> a port, is taking your software and making it available to the *BSD ecosystem, specifically FreeBSD

Oh, very cool! We're not on the *BSD yet, thanks for doing that! 🙂 

> I actually sorted the issue out, I needed to run
>    glib-compile-schemas
> to get the glib schemas to get installed.

Yes, that's needed. It's why I asked you for the specific commands you had run, because I suspected you were missing that step.

Not that the schema is installed by `make install` already, but then a binary version needs to be compiled by `glib-compile-schemas`.

As for your patches, the first one looks entirely harmless, so I'm more than happy to merge it in. In fact, we had already changed that in libcangjie and pycangjie, so I'm surprised we weren't already doing it in ibus-cangjie.

The second one looks problematic though, doesn't that disable the gettext integration?

**Comment by mbridon** [comment]
Hi @igor-kobzev , apologies for not responding before.

First of all, we're in the process of moving this project out of Github and unto gitlab.freedesktop.org as this is a much nicer forge for free software like ours. Please start using the stuff from there instead from now on.

Second, I just merged your first patch to use `#bin/sh` instead of `#/bin/bash`. We had already done that for libcangjie a very long time ago, but never for ibus-cangjie :facepalm: 

This had initially been done by @linquize to support NixOS, so I've now done it for FreeBSD as well. :smile: 

As for the gettext thing, you never answered at the time, doesn't your patch diesble the gettext integration ? That would be undesirable, wouldn't it?

**Comment by mbridon** [comment]
So, you figured out the reason for the error (needed to run `glib-compile-schemas`), we've moved off of Github already and we moved away from the Autotools and onto meson, so we don't have a load of shell (bash/sh) scripts anymore anyway. Closing this issue as a result, and thank you for opening it in the first place. :heart:
